Script started on Thu 24 Jan 2019 09:27:36 PM CST
[?1034hbash-4.2$ pwd
/home/u2/rmn0010/Documents/Software_Construction_COMP_2710
bash-4.2$ ls
a.out  commands.script	testfile.cpp
bash-4.2$ mkdir Assignment_1
bash-4.2$ ls
a.out  Assignment_1  commands.script  testfile.cpp
bash-4.2$ cp commands.script Assignment_1/
bash-4.2$ cd Assignment_1/
bash-4.2$ ls
commands.script
bash-4.2$ cd ..
bash-4.2$ cd Assignment_1/
bash-4.2$ rm commands.script 
bash-4.2$ ls[K[Kcd ..[K[K[K[K[Kls
bash-4.2$ cd ..
bash-4.2$ mv commands.script Assignment_1/
bash-4.2$ ls
a.out  Assignment_1  testfile.cpp
bash-4.2$ cd Assignment_1/
bash-4.2$ ls
commands.script
bash-4.2$ cd ..[K[K[K[K[Kclear
[3;J[H[2Jbash-4.2$ who
rmn0010  pts/0        2019-01-24 21:11 (ettin.eng.auburn.edu)
rmn0010  pts/1        2019-01-24 21:27
dmb0057  pts/2        2019-01-24 20:19 (ettin.eng.auburn.edu)
hnh0004  pts/3        2019-01-17 11:45 (ettin.eng.auburn.edu)
plg0015  pts/5        2019-01-24 20:52 (ettin.eng.auburn.edu)
bash-4.2$ nprov[Kc
16
bash-4.2$ g++ --h
Usage: g++ [options] file...
Options:
  -pass-exit-codes         Exit with highest error code from a phase
  --help                   Display this information
  --target-help            Display target specific command line options
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...]
                           Display specific types of command line options
  (Use '-v --help' to display command line options of sub-processes)
  --version                Display compiler version information
  -dumpspecs               Display all of the built in spec strings
  -dumpversion             Display the version of the compiler
  -dumpmachine             Display the compiler's target processor
  -print-search-dirs       Display the directories in the compiler's search path
  -print-libgcc-file-name  Display the name of the compiler's companion library
  -print-file-name=<lib>   Display the full path to library <lib>
  -print-prog-name=<prog>  Display the full path to compiler component <prog>
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path
  -print-multi-directory   Display the root directory for versions of libgcc
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories
  -print-multi-os-directory Display the relative path to OS libraries
  -print-sysroot           Display the target libraries directory
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers
  -Wa,<options>            Pass comma-separated <options> on to the assembler
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor
  -Wl,<options>            Pass comma-separated <options> on to the linker
  -Xassembler <arg>        Pass <arg> on to the assembler
  -Xpreprocessor <arg>     Pass <arg> on to the preprocessor
  -Xlinker <arg>           Pass <arg> on to the linker
  -save-temps              Do not delete intermediate files
  -save-temps=<arg>        Do not delete intermediate files
  -no-canonical-prefixes   Do not canonicalize paths when building relative
                           prefixes to other gcc components
  -pipe                    Use pipes rather than intermediate files
  -time                    Time the execution of each subprocess
  -specs=<file>            Override built-in specs with the contents of <file>
  -std=<standard>          Assume that the input sources are for <standard>
  --sysroot=<directory>    Use <directory> as the root directory for headers
                           and libraries
  -B <directory>           Add <directory> to the compiler's search paths
  -v                       Display the programs invoked by the compiler
  -###                     Like -v but options quoted and commands not executed
  -E                       Preprocess only; do not compile, assemble or link
  -S                       Compile only; do not assemble or link
  -c                       Compile and assemble, but do not link
  -o <file>                Place the output into <file>
  -pie                     Create a position independent executable
  -shared                  Create a shared library
  -x <language>            Specify the language of the following input files
                           Permissible languages include: c c++ assembler none
                           'none' means revert to the default behavior of
                           guessing the language based on the file's extension

Options starting with -g, -f, -m, -O, -W, or --param are automatically
 passed on to the various sub-processes invoked by g++.  In order to pass
 other options on to these processes the -W<letter> options must be used.

For bug reporting instructions, please see:
<http://bugzilla.redhat.com/bugzilla>.
bash-4.2$ chmod 777 Ass[K[K[Ka[KAsss[K[K[K[K[K[K[K[K[K[K[K[K[K[Kcd ..
bash-4.2$ ls
a.out  Assignment_1  testfile.cpp
bash-4.2$ chmod 777 Assignment_1/
bash-4.2$ ls
a.out  Assignment_1  testfile.cpp
bash-4.2$ Assignment_1/[K[K[K[K[K[K[K[K[K[K[K[K[Kcd Assignment_1/
bash-4.2$ ls
commands.script
bash-4.2$ pwd
/home/u2/rmn0010/Documents/Software_Construction_COMP_2710/Assignment_1
bash-4.2$ exit
exit

Script done on Thu 24 Jan 2019 09:29:43 PM CST
